### ISSUE TITLE
[FEATURE] Configurable shape conversion compatibility check

### ISSUE THREAD

**Issue by psiha** [jfalcou/kiwaku#95]
A macro-based global configuration fine by me :)

**Comment by psiha** [comment]
Not sure what you mean - like have the configuration point be _two_ functions: one for 'are_compatible' check and the other for conversion itself?

**Comment by jfalcou** [comment]
I mean the function can be `convert(shape1,shape2) requires( some stuff based on shape1/2)` so that if shape are not convertible, the convert function fails to compile. Then the converting constructor can just `requires( convert works)`.

YOu write the conversion function and it has requirements that contains the checks.

**Comment by psiha** [comment]
fwiw: just found another one which is a 'matter of preference' (i.e. can only be solved with this 'conversion configuration point') - you have:
    //! @brief Constructs from a shape with a higher order ...... compacting the extra-dimensions
    //! into the last.
 while i need/want only that the extra dimensions be verify to be unit and discarded...

**Comment by psiha** [comment]
ps. we'd probably want that the default kwk conversion logic be available to the user - so that i can delegate to it all the cases 'we agree on' (instead of writing everything myself from scratch)

**Comment by jfalcou** [comment]
Yes we should
